name: Update README

on:
  schedule:
    # Se ejecuta cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: '⚡ Update README with recent activity'
          MAX_LINES: 5
